### ISSUE TITLE
Dedicated theming of terminal apps

### ISSUE THREAD

**Issue by sansmoraxz** [end-4/dots-hyprland#1453]
### What would you like to be added?

I would suggest to theme the terminal apps indivisually rather than printing the sequence file. The sequence file is all inclusive and might not match the overall theme of the application viz. using vscode's or pycharm's integrated terminal.

Matugen would generate the theme viz. use a modfied version of [this](https://github.com/InioX/matugen-themes/blob/main/templates/kitty-colors.conf) on kitty with the matugen toml template like this;

```toml
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
```

and include in kitty conf:

```
# Colors
include colors.conf

# Font
font_family      JetBrains Mono Nerd Font
font_size 11.0
...
```

Same with foot and others.

### How will it help?

No more improper theming while opening any non supported terminal apps or integrated terminals.

### Extra info

Also might I add that the color hues radically changing is quite disconcerting like red success checkmarks for docker compose (while it's green for success; red cross for error)
