### ISSUE TITLE
[Issue]: Change Wallpapers doesn't work, Material colors are not generated, and AGS messes up

### ISSUE THREAD

**Issue by daUnknownCoder** [end-4/dots-hyprland#428]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: 

```bash
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

## The issue
When i change wallpapers with `Ctrl+Super+T`, the wallpaper changes but the color generation messes up

<details>
<summary>Color Generation log, stacktrace file:</summary>

```js
(com.github.Aylur.ags:32461): Gjs-Console-WARNING **: 13:04:10.092: Error: can't assign "hyprland-share-picker" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:40:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:23:14
Icon@resource:///com/github/Aylur/ags/widget.js:26:32
AppButton@file:///home/daUnknownCoder/.config/ags/modules/dock/dock.js:103:35
add@file:///home/daUnknownCoder/.config/ags/modules/dock/dock.js:174:40
Taskbar/setup/<@file:///home/daUnknownCoder/.config/ags/modules/dock/dock.js:199:61
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
_onEvent@resource:///com/github/Aylur/ags/service/hyprland.js:257:26
async*_watchSocket/<@resource:///com/github/Aylur/ags/service/hyprland.js:129:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:32461): Gjs-Console-WARNING **: 13:04:10.096: Error: can't assign "hyprland-share-picker" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:40:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:23:14
Icon@resource:///com/github/Aylur/ags/widget.js:26:32
Window@file:///home/daUnknownCoder/.config/ags/modules/overview/overview_hyprland.js:67:32
default/Workspace/widget.set@file:///home/daUnknownCoder/.config/ags/modules/overview/overview_hyprland.js:289:37
default/OverviewRow/updateWorkspace/<@file:///home/daUnknownCoder/.config/ags/modules/overview/overview_hyprland.js:368:66
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34



(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:31.599: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css



(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:36.388: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css

(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:36.391: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css

(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:36.712: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css


(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:39.029: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css


(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:40.868: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css


(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:43.762: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css


(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:45.599: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css


(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:46.304: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css


(com.github.Aylur.ags:32461): Gjs-Console-CRITICAL **: 13:04:47.225: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/daUnknownCoder/.cache/ags/user/generated/style.css
```
`cat /home/daUnknownCoder/.cache/ags/user/generated/style.css`
```css
/* Error: Undefined variable.
 *   ,
 * 5 | @if $transparent == True {
 *   |     ^^^^^^^^^^^^
 *   '
 *   scss/_colors.scss 5:5  @import
 *   scss/main.scss 9:9     root stylesheet */

body::before {
  font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
      "Droid Sans Mono", monospace, monospace;
  white-space: pre;
  display: block;
  padding: 1em;
  margin-bottom: 1em;
  border-bottom: 2px solid black;
  content: "Error: Undefined variable.\a   \2577 \a 5 \2502  @if $transparent == True {\a   \2502      ^^^^^^^^^^^^\a   \2575 \a   scss/_colors.scss 5:5  @import\a   scss/main.scss 9:9     root stylesheet";
}
```
</details>

https://github.com/end-4/dots-hyprland/assets/84800625/117da6bc-d8b0-4eff-b3f3-577c3d497be3

and see in the video, the generated colors are pink and the warm tones, the wallpaper is blue and cool toned...
